language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

branches:
  only:
  - master

notifications:
  email:
    recipients:
    - zeek-commits-internal@zeek.org

script: make test

after_failure: cat testing/diag.log
