cpus: &CPUS 8
memory: &MEMORY 6GB

config: &CONFIG --build-type=release

resources_template: &RESOURCES_TEMPLATE
  cpu: *CPUS
  memory: *MEMORY

ci_template: &CI_TEMPLATE
  only_if: >
    $CIRRUS_PR != '' ||
    $CIRRUS_BRANCH == 'master' ||
    $CIRRUS_BRANCH =~ 'release/.*'

  sync_submodules_script: git submodule update --recursive --init
  build_script: ./ci/build.sh
  test_script: ./ci/test.sh

env:
  CIRRUS_WORKING_DIR: /broker
  BROKER_CI_CPUS: *CPUS
  BROKER_CI_CONFIGURE_FLAGS: *CONFIG

# Linux EOL timelines: https://linuxlifecycle.com/
# Fedora (~13 months): https://fedoraproject.org/wiki/Fedora_Release_Life_Cycle

fedora30_task:
  container:
    # Fedora 30 EOL: Around June 2020
    dockerfile: ci/fedora-30/Dockerfile
    << : *RESOURCES_TEMPLATE
  << : *CI_TEMPLATE

centos7_task:
  container:
    # CentOS 7 EOL: June 30, 2024
    dockerfile: ci/centos-7/Dockerfile
    << : *RESOURCES_TEMPLATE
  << : *CI_TEMPLATE

debian9_task:
  container:
    # Debian 9 EOL: June 2022
    dockerfile: ci/debian-9/Dockerfile
    << : *RESOURCES_TEMPLATE
  << : *CI_TEMPLATE

debian9_32bit_task:
  container:
    # Debian 9 EOL: June 2022
    dockerfile: ci/debian-9-32bit/Dockerfile
    << : *RESOURCES_TEMPLATE
  << : *CI_TEMPLATE

ubuntu18_task:
  container:
    # Ubuntu 18.04 EOL: April 2023
    dockerfile: ci/ubuntu-18.04/Dockerfile
    << : *RESOURCES_TEMPLATE
  << : *CI_TEMPLATE

ubuntu16_task:
  container:
    # Ubuntu 16.04 EOL: April 2021
    dockerfile: ci/ubuntu-16.04/Dockerfile
    << : *RESOURCES_TEMPLATE
  << : *CI_TEMPLATE

# Apple doesn't publish official long-term support timelines, so easiest
# option is to only support the latest macOS release or whatever latest
# image is available.
macos_task:
  osx_instance:
    image: catalina-base
    # cpu/memory setting is implicitly 2 core / 4 thread and 8GB, and
    # trying to set it explicitly results in an error.
  prepare_script: ./ci/macos/prepare.sh
  << : *CI_TEMPLATE
  env:
    BROKER_CI_CPUS: 4
    # No permission to write to default location of /broker
    CIRRUS_WORKING_DIR: /tmp/broker

# FreeBSD EOL timelines: https://www.freebsd.org/security/security.html#sup
freebsd_task:
  freebsd_instance:
    # FreeBSD 12 EOL: June 30, 2024
    image_family: freebsd-12-1
    cpu: 8
    # Not allowed to request less than 8GB for an 8 CPU FreeBSD VM.
    memory: 8GB
  prepare_script: ./ci/freebsd/prepare.sh
  << : *CI_TEMPLATE
